import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const source = readFileSync(new URL('./FeaturesPage.vue', import.meta.url), 'utf-8')

describe('FeaturesPage card actions', () => {
  it('uses the migrated project preview card and collapsible group styles', () => {
    expect(source).toContain('class="feature-group-header"')
    expect(source).toContain('@click="toggleFeatureGroup(section.group)"')
    expect(source).toContain('class="product-card group/card"')
    expect(source).toContain('class="product-card__preview-cover"')
    expect(source).toContain('class="product-card__preview-icon"')
    expect(source).not.toContain('>SAAS</span>')
    expect(source).toContain('class="product-card__meta"')
    expect(source).toContain('formatFeatureModifiedAt(card.modifiedAt)')
  })

  it('keeps PM project cards functionally aligned with UX project cards', () => {
    expect(source).toContain('async function renameFeature(card: FeatureCard): Promise<void>')
    expect(source).toContain("'feature.rename'")
    expect(source).toContain('async function moveFeatureToGroup(card: FeatureCard): Promise<void>')
    expect(source).toContain("'feature.move'")
    expect(source).toContain('function featureMoveOptions(card: FeatureCard)')
    expect(source).toContain('options: featureMoveOptions(card)')
    expect(source).toContain("value: UNGROUPED_GROUP_VALUE")
    expect(source).not.toContain('填分组名（可新建）')
    expect(source).toContain('async function createGroup(): Promise<void>')
    expect(source).toContain('async function renameGroup(group: string): Promise<void>')
    expect(source).toContain('function deleteGroup(group: string, featureCount: number): void')
    expect(source).toContain('@select="deleteGroup(section.group, section.items.length)"')
    expect(source).toContain("'feature.listGroups'")
    expect(source).toContain('async function copyFeature(card: FeatureCard): Promise<void>')
    expect(source).toContain("'editor.copyEntry'")
    expect(source).toContain('async function copyFeatureToSpace(card: FeatureCard): Promise<void>')
    expect(source).toContain("'feature.copyToSpace'")
    expect(source).toContain('type CopySpaceCandidate = {')
    expect(source).toContain('async function loadCopySpaceCandidates(): Promise<CopySpaceCandidate[]>')
    expect(source).toContain("const workspaces = ws.list.filter((item) => !item.hidden && item.kind === 'project' && supportsPersonalSpaces(item))")
    expect(source).toContain('value: copySpaceValue(workspace.id, space.slug)')
    expect(source).toContain('options: candidates.map((candidate) => ({')
    expect(source).toContain('label: `${candidate.workspaceName} / ${personalSpaceLabel(candidate.space)}`')
    expect(source).toContain("const targetName = await askCopyToSpaceTargetName(card.name)")
    expect(source).toContain('targetName')
    expect(source).toContain('value: candidate.value')
    expect(source).toContain('description: candidate.space.branch')
    expect(source).toContain('targetWorkspaceId: target.workspaceId')
    expect(source).toContain('targetSlug: target.space.slug')
    expect(source).not.toContain('findPersonalSpaceByInput')
    expect(source).not.toContain('class="feature-card__share-button"')
    expect(source).not.toContain('class="feature-card__publish-tag"')
    expect(source).not.toContain('OpenWithMenu')
    expect(source).not.toContain('>发布</Button>')
    expect(source).not.toContain('已发布')
    expect(source).toContain('import ProjectCardMoreMenu from')
    expect(source).not.toContain('@edit="openFeatureProject(card)"')
    expect(source).not.toContain('>编辑</Button>')
    expect(source).toContain('@rename="renameFeature(card)"')
    expect(source).toContain('@move="moveFeatureToGroup(card)"')
    expect(source).toContain('@copy="copyFeature(card)"')
    expect(source).not.toContain('@copy-to-space="copyFeatureToSpace(card)"')
    expect(source).not.toContain('@team-space="pushFeatureToTeamSpace(card)"')
    expect(source).toContain('@click="createGroup"')
    expect(source).toContain('@select="renameGroup(section.group)"')
  })
})
