import { describe, expect, it } from 'vitest'
import { normalizeClaudeEvent } from './claude-event-normalizer'

describe('claude-event-normalizer', () => {
  it('ignores resume meta user event and synthetic no-response assistant event', () => {
    const meta = normalizeClaudeEvent({
      type: 'user',
      uuid: 'u-meta',
      isMeta: true,
      message: { role: 'user', content: [{ type: 'text', text: 'Continue from where you left off.' }] }
    })
    const synthetic = normalizeClaudeEvent({
      type: 'assistant',
      uuid: 'a-synthetic',
      message: {
        id: 'synthetic-id',
        model: '<synthetic>',
        role: 'assistant',
        content: [{ type: 'text', text: 'No response requested.' }]
      }
    })

    expect(meta).toEqual([{ type: 'ignore', reason: 'internal-meta' }])
    expect(synthetic).toEqual([{ type: 'ignore', reason: 'synthetic-no-response' }])
  })

  it('normalizes real user text', () => {
    expect(normalizeClaudeEvent({
      type: 'user',
      uuid: 'u1',
      message: { role: 'user', content: [{ type: 'text', text: '继续' }] }
    })).toEqual([{
      type: 'message.user',
      uuid: 'u1',
      content: [{ type: 'text', text: '继续' }]
    }])
  })

  it('strips internal prompt context from visible user text only when generated by the app', () => {
    const generated = [
      '## 当前编辑文档',
      '',
      '目标文件：`测试pred.md`',
      '',
      '## 用户指令',
      '',
      '分析一下这个 PRD'
    ].join('\n')

    expect(normalizeClaudeEvent({
      type: 'user',
      uuid: 'u-generated',
      message: { role: 'user', content: [{ type: 'text', text: generated }] }
    })).toEqual([{
      type: 'message.user',
      uuid: 'u-generated',
      content: [{ type: 'text', text: '分析一下这个 PRD' }]
    }])

    const literal = ['## 用户指令', '', '这是用户自己输入的标题'].join('\n')
    expect(normalizeClaudeEvent({
      type: 'user',
      uuid: 'u-literal',
      message: { role: 'user', content: [{ type: 'text', text: literal }] }
    })).toEqual([{
      type: 'message.user',
      uuid: 'u-literal',
      content: [{ type: 'text', text: literal }]
    }])
  })

  it('strips workspace-scope and knowledge-base prompt headers (A6 / KB injection)', () => {
    // workspace-home design-prd 模式：## 当前分支工作范围 + ## 用户指令
    const designPrdPrompt = [
      '## 当前分支工作范围',
      '',
      '可写范围：`docs/` 和 `ui/`。',
      '',
      '## 用户指令',
      '',
      '帮我画登录页'
    ].join('\n')
    expect(normalizeClaudeEvent({
      type: 'user',
      uuid: 'u-prd',
      message: { role: 'user', content: [{ type: 'text', text: designPrdPrompt }] }
    })).toEqual([{
      type: 'message.user',
      uuid: 'u-prd',
      content: [{ type: 'text', text: '帮我画登录页' }]
    }])

    // 知识库注入也要被擦
    const kbPrompt = [
      '## 可用知识库',
      '',
      '- @design-system（UI 资产）：`.external/design-system/`',
      '',
      '## 用户指令',
      '',
      '参考 design-system 改一下颜色'
    ].join('\n')
    expect(normalizeClaudeEvent({
      type: 'user',
      uuid: 'u-kb',
      message: { role: 'user', content: [{ type: 'text', text: kbPrompt }] }
    })).toEqual([{
      type: 'message.user',
      uuid: 'u-kb',
      content: [{ type: 'text', text: '参考 design-system 改一下颜色' }]
    }])
  })

  it('normalizes UI approval continuation as resolved state instead of a visible user message', () => {
    expect(normalizeClaudeEvent({
      type: 'user',
      uuid: 'u-approval',
      message: {
        role: 'user',
        content: [{
          type: 'text',
          text: [
            '我已在 UI 中授权执行下面这条 Bash 命令。',
            '请继续完成原任务。',
            '',
            'find . -name "*.md" | head'
          ].join('\n')
        }]
      }
    })).toEqual([{
      type: 'approval.resolved',
      uuid: 'u-approval',
      decision: 'allow'
    }])
  })

  it('normalizes assistant chunks with provider message ids', () => {
    const events = normalizeClaudeEvent({
      type: 'assistant',
      uuid: 'a-tool',
      message: {
        id: 'msg-1',
        role: 'assistant',
        content: [{ type: 'tool_use', id: 'tool-1', name: 'TaskCreate', input: { subject: '写 PRD' } }]
      }
    }, { assistantInFlight: true })

    expect(events).toEqual([{
      type: 'message.assistant',
      uuid: 'a-tool',
      providerMessageId: 'msg-1',
      inFlight: true,
      content: [{ type: 'tool_use', toolUseId: 'tool-1', name: 'TaskCreate', input: { subject: '写 PRD' } }]
    }])
  })

  it('normalizes user tool_result separately from real user messages', () => {
    expect(normalizeClaudeEvent({
      type: 'user',
      uuid: 'u-result',
      message: {
        role: 'user',
        content: [{ type: 'tool_result', tool_use_id: 'tool-1', content: 'ok', is_error: false }]
      }
    })).toEqual([{
      type: 'tool.result',
      uuid: 'u-result',
      content: [{ type: 'tool_result', toolUseId: 'tool-1', content: 'ok', isError: false }]
    }])
  })

  it('normalizes result event into turn completion', () => {
    // stream-json 真实 success 形态：is_error=false，result 是模型最终文本
    // （工具收尾的 turn 里这是唯一结论文本，随事件带给 reducer 落地）
    expect(normalizeClaudeEvent({
      type: 'result',
      subtype: 'success',
      uuid: 'r1',
      is_error: false,
      result: '这是模型最终回复'
    })).toEqual([{ type: 'turn.completed', uuid: 'r1', status: 'completed', finalText: '这是模型最终回复' }])
  })

  it('surfaces stream-json result errors via the result field', () => {
    expect(normalizeClaudeEvent({
      type: 'result',
      subtype: 'error_during_execution',
      uuid: 'r-error',
      is_error: true,
      result: 'API key is missing'
    })).toEqual([{
      type: 'turn.completed',
      uuid: 'r-error',
      status: 'error',
      errorMessage: 'API key is missing'
    }])
  })

  it('falls back to subtype when error result has no message body', () => {
    expect(normalizeClaudeEvent({
      type: 'result',
      subtype: 'error_max_turns',
      uuid: 'r-empty',
      is_error: true
    })).toEqual([{
      type: 'turn.completed',
      uuid: 'r-empty',
      status: 'error',
      errorMessage: 'Claude 执行失败：error_max_turns'
    }])
  })

  // P4：stream_event 归一化（--include-partial-messages 开启后才有）
  describe('stream_event normalization', () => {
    it('converts content_block_delta text_delta to text.delta', () => {
      const out = normalizeClaudeEvent({
        type: 'stream_event',
        uuid: 'se-1',
        event: {
          type: 'content_block_delta',
          index: 0,
          delta: { type: 'text_delta', text: 'Hello' }
        }
      })
      expect(out).toEqual([{ type: 'text.delta', uuid: 'se-1', delta: 'Hello' }])
    })

    it('ignores content_block_delta with empty text', () => {
      const out = normalizeClaudeEvent({
        type: 'stream_event',
        uuid: 'se-2',
        event: { type: 'content_block_delta', delta: { type: 'text_delta', text: '' } }
      })
      expect(out[0].type).toBe('ignore')
    })

    it('ignores input_json_delta (tool_use streaming) — dedupe via assistant wrapper only', () => {
      const out = normalizeClaudeEvent({
        type: 'stream_event',
        uuid: 'se-3',
        event: {
          type: 'content_block_delta',
          index: 1,
          delta: { type: 'input_json_delta', partial_json: '{"file_path":' }
        }
      })
      expect(out[0].type).toBe('ignore')
    })

    it('ignores thinking_delta (no streaming thinking yet)', () => {
      const out = normalizeClaudeEvent({
        type: 'stream_event',
        uuid: 'se-4',
        event: { type: 'content_block_delta', delta: { type: 'thinking_delta', thinking: 'hmm' } }
      })
      expect(out[0].type).toBe('ignore')
    })

    it('ignores message_start / content_block_start / message_stop', () => {
      for (const evType of ['message_start', 'content_block_start', 'content_block_stop', 'message_stop']) {
        const out = normalizeClaudeEvent({
          type: 'stream_event',
          uuid: 'se-5',
          event: { type: evType }
        })
        expect(out[0].type).toBe('ignore')
      }
    })

    it('handles malformed stream_event gracefully', () => {
      const out = normalizeClaudeEvent({
        type: 'stream_event',
        uuid: 'se-6',
        event: {}   // 无 type
      })
      expect(out[0].type).toBe('ignore')
    })
  })
})

describe('result 事件 finalText 提取', () => {
  it('success 时把 result 字段作为 finalText 带出', () => {
    const out = normalizeClaudeEvent({
      type: 'result',
      subtype: 'success',
      is_error: false,
      result: '页面已生成完毕，共三个状态。'
    } as never)
    expect(out[0]).toMatchObject({ type: 'turn.completed', status: 'completed', finalText: '页面已生成完毕，共三个状态。' })
  })

  it('error 时不带 finalText，只带 errorMessage', () => {
    const out = normalizeClaudeEvent({
      type: 'result',
      is_error: true,
      result: 'API Error: 400'
    } as never)
    expect(out[0]).toMatchObject({ type: 'turn.completed', status: 'error', errorMessage: 'API Error: 400' })
    expect((out[0] as { finalText?: string }).finalText).toBeUndefined()
  })

  it('空 result 文本不带 finalText', () => {
    const out = normalizeClaudeEvent({ type: 'result', subtype: 'success', result: '   ' } as never)
    expect((out[0] as { finalText?: string }).finalText).toBeUndefined()
  })
})
